services:
  - type: web
    name: alphy-coordinator
    env: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: SOAP_LOGIN
        sync: false
      - key: SOAP_PASSWORD
        sync: false
