services:
  - type: web
    name: alphy-coordinator
    env: docker
    plan: free
    healthCheckPath: /api/nodes
    envVars:
      - key: NODE_SECRET
        sync: false
      - key: NODES_CONFIG
        sync: false
